services:
  n8n:
    build: ./n8n-extensions
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/New_York
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
      # Ollama connection via Windows host
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - vc-mgr_n8n_data:/home/node/.n8n
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: n8n_redis
    restart: unless-stopped
    volumes:
      - vc-mgr_redis_data:/data

  n8n-mcp:
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    container_name: n8n-mcp
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # Mode configuration
      - MCP_MODE=http
      - USE_FIXED_HTTP=true
      - AUTH_TOKEN=${N8N_MCP_AUTH_TOKEN:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.n8nmcp.server.token}
      
      # Application settings
      - NODE_ENV=development
      - LOG_LEVEL=info
      - PORT=3001
      
      # Database configuration
      - NODE_DB_PATH=/app/data/nodes.db
      - REBUILD_ON_START=false
      
      # n8n API integration (enables 16 additional management tools)
      - N8N_API_URL=http://n8n:5678
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_API_TIMEOUT=30000
      - N8N_API_MAX_RETRIES=3
    volumes:
      - vc-mgr_n8n_mcp_data:/app/data
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  sqlite-web-viewer:
    image: coleifer/sqlite-web
    container_name: sqlite-web-viewer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - vc-mgr_n8n_data:/data
    environment:
      - SQLITE_DATABASE=/data/database.sqlite
    depends_on:
      - n8n

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - vc-mgr_open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  vc-mgr_n8n_data:
    external: true
  vc-mgr_redis_data:
    external: true
  vc-mgr_n8n_mcp_data:
    external: true
  vc-mgr_open_webui_data:
    external: true